management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  tracing:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false

logging:
  level:
    com.vmware.tanzu.demos: DEBUG
