apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wnisb3-native
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
configMapGenerator:
- name: app
  literals:
  - app.message=Hello from a native Kubernetes app!
