apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wnisb3-otel
resources:
- namespace.yaml
- kapp.yaml
- kservice.yaml
- otel.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: app
  literals:
  - app.services.orders=http://orders.wnisb3-otel.svc.cluster.local
  - app.services.items=http://items.wnisb3-otel.svc.cluster.local
  - management.otlp.metrics.export.step=4s
  - management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
  - management.tracing.sampling.probability=1.0
  - management.zipkin.tracing.endpoint=http://otel-collector:9411/api/v2/spans
