management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    enabled: true
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.vmware.tanzu.demos: INFO
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){yellow} %clr(:){red} %clr(%m){faint}%n"

spring:
  application:
    name: wnisb3-otel-items
server:
  port: ${PORT:8082}
