management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    enabled: true
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.vmware.tanzu.demos: INFO
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){yellow} %clr(:){red} %clr(%m){faint}%n"

server:
  port: ${PORT:8080}

spring:
  application:
    name: wnisb3-otel-shop
  cloud:
    discovery:
      client:
        simple:
          instances:
            orders:
            - uri: http://localhost:8081
            items:
            - uri: http://localhost:8082

app:
  title: Welcome to SpringBootShop!
