name: wnisb3-otel-shop

on:
  push:
    branches:
    - main
    - testing
    paths:
    - otel/shop/**
    - otel/pom.xml
    - .github/workflows/_test.yaml
    - .github/workflows/_deploy.yaml
    - .github/workflows/wnisb3-otel-shop.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-test-app:
    if: always()
    uses: ./.github/workflows/_test.yaml
    with:
      working-directory: otel
      module: shop

  call-deploy-image:
    needs:
    - call-test-app
    uses: ./.github/workflows/_deploy.yaml
    with:
      working-directory: otel
      module: shop
      native: true
