name: wnisb3-native

on:
  push:
    branches:
    - main
    - testing
    paths:
    - native/**
    - .github/workflows/_test.yaml
    - .github/workflows/_deploy.yaml
    - .github/workflows/wnisb3-native.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-test-app:
    if: always()
    uses: ./.github/workflows/_test.yaml
    with:
      working-directory: native

  call-deploy-image:
    needs:
    - call-test-app
    uses: ./.github/workflows/_deploy.yaml
    with:
      working-directory: native
      native: true
